disabled_rules:
  - trailing_whitespace
  - variable_name
  - todo
  - type_name
  - function_parameter_count
  - type_body_length
  - function_body_length
  - file_length
  - line_length
  - nesting
  - cyclomatic_complexity
  - control_statement
  - private_over_fileprivate

opt_in_rules:
  - private_outlet

force_unwrapping:
  severity: error

trailing_comma:
  mandatory_comma: true

excluded:
  - Pods
  - LaFinBox-ComponentsTests
  - LaFinBox-CoreTests
  - R.generated.swift
